export const SQLITE_SCHEMA = [
  `create table if not exists events (
    seq integer primary key autoincrement,
    id text not null unique,
    type text not null,
    time integer not null,
    session_id text,
    thread_id text,
    payload_json text not null
  )`,
  `create unique index if not exists events_id_idx on events(id)`,
  `create index if not exists events_seq_idx on events(seq)`,
  `create index if not exists events_session_seq_idx on events(session_id, seq)`,
  `create index if not exists events_thread_seq_idx on events(thread_id, seq)`,
  `create index if not exists events_type_seq_idx on events(type, seq)`,
  `create index if not exists events_session_time_idx on events(session_id, time, id)`,
  `create index if not exists events_thread_time_idx on events(thread_id, time, id)`,
  `create index if not exists events_type_time_idx on events(type, time, id)`,

  `create table if not exists sessions (
    id text primary key,
    cwd text not null,
    title text,
    status text not null,
    created_at integer not null,
    updated_at integer not null
  )`,
  `create index if not exists sessions_updated_idx on sessions(updated_at)`,

  `create table if not exists thread_goals (
    thread_id text primary key,
    session_id text,
    objective text not null,
    status text not null,
    token_budget integer,
    tokens_used integer not null default 0,
    time_used_seconds real not null default 0,
    created_at integer not null,
    updated_at integer not null,
    completed_at integer,
    last_reason text
  )`,
  `create index if not exists thread_goals_session_idx on thread_goals(session_id)`,
  `create index if not exists thread_goals_status_idx on thread_goals(status, updated_at)`,

  `create table if not exists messages (
    id text primary key,
    session_id text not null,
    thread_id text,
    turn_id text,
    role text not null,
    parent_id text,
    created_at integer not null
  )`,
  `create index if not exists messages_session_time_idx on messages(session_id, created_at, id)`,

  `create table if not exists message_parts (
    id text primary key,
    message_id text not null,
    session_id text not null,
    type text not null,
    ordinal integer not null,
    data_json text not null,
    created_at integer not null
  )`,
  `create index if not exists message_parts_message_ordinal_idx on message_parts(message_id, ordinal)`,
  `create index if not exists message_parts_session_idx on message_parts(session_id)`,

  `create table if not exists tool_calls (
    id text primary key,
    session_id text,
    thread_id text,
    turn_id text,
    tool_name text not null,
    status text not null,
    input_json text,
    output text,
    error text,
    synthetic integer not null default 0,
    started_at integer not null,
    updated_at integer not null
  )`,
  `create index if not exists tool_calls_session_status_idx on tool_calls(session_id, status)`,
  `create index if not exists tool_calls_turn_idx on tool_calls(turn_id)`,

  `create table if not exists approvals (
    id text primary key,
    session_id text,
    thread_id text,
    call_id text,
    permission text not null,
    patterns_json text not null,
    metadata_json text,
    status text not null,
    decision text,
    feedback text,
    created_at integer not null,
    resolved_at integer
  )`,
  `create index if not exists approvals_session_status_idx on approvals(session_id, status)`,
  `create index if not exists approvals_call_idx on approvals(call_id)`,

  `create table if not exists agent_runs (
    id text primary key,
    session_id text,
    thread_id text,
    task_id text,
    path text not null,
    parent_path text,
    parent_session_id text,
    parent_thread_id text,
    child_session_id text,
    child_thread_id text,
    task_name text not null,
    cwd text,
    mode text,
    status text not null,
    generation integer not null default 0,
    created_at integer not null,
    completed_at integer
  )`,
  `create index if not exists agent_runs_session_status_idx on agent_runs(session_id, status)`,
  `create index if not exists agent_runs_path_idx on agent_runs(path)`,

  `create table if not exists agent_tasks (
    id text primary key,
    path text not null,
    parent_path text,
    parent_session_id text,
    parent_thread_id text,
    child_session_id text,
    child_thread_id text,
    task_name text not null,
    cwd text,
    prompt text,
    mode text,
    status text not null,
    generation integer not null default 0,
    current_run_id text,
    summary text,
    error text,
    completion_json text,
    lease_owner text,
    lease_expires_at integer,
    lease_heartbeat_at integer,
    created_at integer not null,
    updated_at integer not null,
    completed_at integer
  )`,
  `create index if not exists agent_tasks_path_idx on agent_tasks(path)`,
  `create index if not exists agent_tasks_parent_session_status_idx on agent_tasks(parent_session_id, status)`,
  `create index if not exists agent_tasks_child_session_idx on agent_tasks(child_session_id)`,

  `create table if not exists agent_mailbox (
    id text primary key,
    task_id text,
    path text not null,
    from_path text not null,
    child_session_id text,
    child_thread_id text,
    trigger_turn integer not null,
    status text not null,
    message_json text,
    created_at integer not null,
    consumed_at integer
  )`,
  `create index if not exists agent_mailbox_task_idx on agent_mailbox(task_id, created_at)`,
  `create index if not exists agent_mailbox_path_idx on agent_mailbox(path, created_at)`,
  `create index if not exists agent_mailbox_child_session_idx on agent_mailbox(child_session_id, created_at)`,
  `create index if not exists agent_mailbox_status_idx on agent_mailbox(status, created_at)`,

  `create table if not exists teams (
    id text primary key,
    session_id text,
    name text not null,
    lead_path text not null,
    status text not null,
    description text,
    created_at integer not null,
    updated_at integer not null
  )`,
  `create index if not exists teams_session_idx on teams(session_id)`,

  `create table if not exists team_members (
    team_id text not null,
    path text not null,
    name text not null,
    role text not null,
    status text not null,
    child_session_id text,
    child_thread_id text,
    model text,
    tool_scope_json text,
    write_scope_json text,
    current_task_id text,
    created_at integer not null,
    updated_at integer not null,
    closed_at integer,
    primary key (team_id, path)
  )`,
  `create index if not exists team_members_team_status_idx on team_members(team_id, status)`,
  `create index if not exists team_members_path_idx on team_members(path)`,

  `create table if not exists team_tasks (
    id text primary key,
    team_id text not null,
    session_id text,
    owner_path text,
    status text not null,
    title text,
    description text,
    created_by text,
    depends_on_json text,
    summary text,
    error text,
    metadata_json text,
    created_at integer not null,
    updated_at integer not null,
    completed_at integer
  )`,
  `create index if not exists team_tasks_team_status_idx on team_tasks(team_id, status)`,
  `create index if not exists team_tasks_owner_status_idx on team_tasks(owner_path, status)`,

  `create table if not exists team_messages (
    id text primary key,
    team_id text not null,
    from_path text not null,
    to_path text not null,
    task_id text,
    kind text not null,
    delivery text,
    content text not null,
    summary text,
    metadata_json text,
    created_at integer not null
  )`,
  `create index if not exists team_messages_team_time_idx on team_messages(team_id, created_at)`,
  `create index if not exists team_messages_to_time_idx on team_messages(to_path, created_at)`,
  `create index if not exists team_messages_task_idx on team_messages(task_id, created_at)`,

  `create table if not exists team_message_deliveries (
    mailbox_message_id text primary key,
    team_id text not null,
    team_message_id text not null,
    path text not null,
    child_session_id text,
    child_thread_id text,
    trigger_turn integer not null,
    status text not null,
    error text,
    queued_at integer not null,
    updated_at integer not null,
    delivered_at integer
  )`,
  `create index if not exists team_message_deliveries_team_idx on team_message_deliveries(team_id, updated_at)`,
  `create index if not exists team_message_deliveries_message_idx on team_message_deliveries(team_message_id, updated_at)`,
  `create index if not exists team_message_deliveries_status_idx on team_message_deliveries(status, updated_at)`,
];
